# -*- coding: utf-8 -*-
"""Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqOH7Idk8SEn-TfmoH93srdKO7piK__J
"""

import random
emojis = ["Skate","arte","fotografia"]
print(random.choice(emojis))

meme_dict = {
            "CRINGE": "Algo excepcionalmente raro o embarazoso",
            "LOL": "Una respuesta común a algo gracioso",
            "CHIMBITA" : "Algo que esta muy chevere",
            }

word = input("Escribe una palabra que no entiendas (¡con mayúsculas!): ")

if word in meme_dict.keys():
    print(meme_dict[word])
else:
    print("Todavía no tenemos esta palabra... Pero estamos trabajando en ella.")