# -*- coding: utf-8 -*-
"""listaDePasatiempos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqOH7Idk8SEn-TfmoH93srdKO7piK__J
"""

import random
emojis = ["Skate","arte","fotografia"]
print(random.choice(emojis))